### ISSUE TITLE
unlockItemAfterCommit should add ConditionExpression that "Applied" is true for Put and Update requests

### ISSUE THREAD

**Issue by fumin** [awslabs/dynamodb-transactions#31]
Logically speaking, a prerequisite for unlocking items after a commit, is for all changes to be applied.
Therefore, the should be a ConditionExpression in

https://github.com/awslabs/dynamodb-transactions/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/transactions/Transaction.java#L649

that checks that `AttributeName.APPLIED` is true.

Without this ConditionExpression there can be race conditions when there are resumed transactions that try to add requests instead of always rolling back, or put differently, there are multiple coordinators working on the same transaction.
In particular, there might be the case, which is similar to https://github.com/awslabs/dynamodb-transactions/pull/27 , where:

* transaction1 contains 5 requests that have been applied.
* coordinator1 reads transaction1 and thinks it contains 5 requests.
* coordinator2 adds a 6th request to transaction1 and locked the reference item, but has yet to apply it.
* coordinator1 marks transaction1 as committed.
* coordinator2 fails to apply the 6th request.
* coordinator1 releases the lock on the item referenced by the 6th request.
* Error: transaction1 says the all 6 requests have been committed, whereas in reality only the first 5 have.

This seems to suggest that not only do we need the the check on APPLIED, but we also need to ensure that there can be only a single coordinator that adds requests to transactions. In other words, all resumed transactions or all coordinators except the initiator should be only allowed to rollback transactions.

**Comment by Yanacek** [comment]
Thanks for diving deep on the transaction library! Having this specific list of steps describing the scenario makes it really easy to talk about the behavior.

It does seem like the multi-coordinator case is not particularly useful (other than for rolling back), and in retrospect leads to unnecessary complexity which open the door to possible bugs. However, a comment about this particular scenario:

-     transaction1 contains 5 requests that have been applied. (let's say tx1's version number is "6")
-     coordinator1 reads transaction1 and thinks it contains 5 requests. (coordinator1 reads tx1's version="6")
-     coordinator2 adds a 6th request to transaction1 and locked the reference item, but has yet to apply it. (coordinator 2's update to tx1 updates its version number to "7", conditioning on it still being "6")
-     coordinator1 marks transaction1 as committed. (however, this fails, because coordinator1 conditions on tx1's version number ="6", but it is now "7", so this fails.
-     coordinator2 fails to apply the 6th request. (let's say coordinator2 crashes forever now)
-     coordinator1 re-reads tx1, seeing that its version = "7".
-     coordinator1 retries its commit(), but before writing "committed" to the tx item, it [calls verifyLocks()](https://github.com/awslabs/dynamodb-transactions/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/transactions/Transaction.java#L499), which performs coordinator2's apply() again.
-     coordinator1 calls commit, upping the tx item's version to "8" (the conditional check passes because it conditioned on version="7").
-     coordinator1 releases the lock on the item referenced by the 6th request. (which how has been correctly applied)
-     Result: all items have been applied and unlocked, and the transaction is committed.

The integration test for this particular case is in [resumeAndCommitAfterTransientApplyFailure](https://github.com/awslabs/dynamodb-transactions/blob/master/integration/src/test/java/com/amazonaws/services/dynamodbv2/transactions/TransactionsIntegrationTest.java#L1256).

Now it would make sense to do as you describe (only unlock items after commit if they're applied, using a conditional expression), if even as a "belt and suspenders" approach to protect against bugs. However, there are some practical challenges. The biggest challenge is that transient locks (such as locks for read or delete of non-existent items) do not get marked as applied today. Therefore the logic would have to be "upgrade safe" for other users of the tx library to deploy safely without causing items to become stuck during their upgrade. Even beyond the upgrade considerations, we'd have to be careful with the fact that items can be upgraded from read locks to write locks (a handy feature, but another one that adds complexity to the library), and with the fact that transactions can be migrated between transaction managers (which is challenging along with the fact that writes can be upgraded from read to write locks). 

So given that it would be pretty tricky to add these extra safety checks (especially in an upgrade-safe way), and because it doesn't seem like there are any existing correctness bugs, it seems like we should pass on making any changes around this. Can you think of any other scenarios that could cause an item to be unlocked without being applied? I'll chew on it too, but if we can't come up with cases demonstrating a bug, I'd like to resolve this issue.

Thanks again for the detailed report, and putting the time into thinking about edge cases in the library!

**Comment by fumin** [comment]
Hi Yanacek

Thanks for your thorough explanation!
About the issue with multiple coordinators, I realized I missed the fact that coordinators always do a `verifyLocks`, which actually not only acquire locks, but also perhaps most importantly apply changes to items, before it updates the state of a transaction to committed. In other words, the algorithm guarantees that whenever a transaction is in state committed, all requests contained by it have gone through `applyAndKeepLocks` successfully.

In this case, I wonder could you confirm that ignoring the "upgrade safe" concern for the moment, it is actually correct to add a condition expression for Put and Update requests in `unlockAfterCommit`, i.e.  "Transaction.java#L649"? Apologies for being a bit too paranoid, but I just want to make sure it is correct to add this check in a Go version of this library I am working on.

Aside from the above request for confirmation, I think this implementation is as faithful to the algorithm as it should be. Thanks again for releasing this useful library!

**Comment by Yanacek** [comment]
Adding the extra "IsApplied" conditional check expression isn't going to work quite right with the java library, but it would work if you drop support for resuming transactions (except to roll back) in the GO library to make it work.

Here's the flow that would break if an IsApplied=true conditional check were added to "unlock" after a tx is committed:

Coordinator C1 begins Transaction T1
C1 adds a GetItem request for item I1 to T1
C1 pauses for a bit (its next step is lock I1, but it hasn't done that yet)
Coordinator C2 resumes Transation T2
C2 adds an PutItem request P1 for I1
C2 updates I1 with a lock, and the modification, and marks it IsApplied=true (this might be multiple steps, but let's say it does all of those things without interference)
C2 commits the transaction, and unlocks I1
C1 wakes up again and locks I1 with a read lock
C1 re-reads the TX item, sees that it's committed
C1 calls doCommit(), which again re-reads the TX item (probably not necessary in every case, but that's today's behavior)
C1 calls unlockItemAfterCommit (today it's fine, but if we conditioned on IsApplied there'd be a problem)

Here's the problem: We're discussing adding adding a check to make sure that we've applied writes when we release the lock. But in this case, because of the timing of two transaction managers, the transaction is committed, but there's another transaction that came in earlier that's "re-locking" an item from the transaction, but it's already been applied and unlocked by the first transaction to win the race. Therefore the right thing to do in this case is to release the lock, which is the current behavior.

A major simplifying improvement to the library would be to drop support for resuming transactions in new coordinators. If I were you, I'd make the Go library NOT support a second coordinator modifying a transaction OTHER than rolling it back. It makes some of these extra conditional checks possible (but if you do the conditional check, be careful about having the Java version and the Go version both working on the same table.)

**Comment by fumin** [comment]
Thanks for providing the exact scenario in which the check on APPLIED leads to failures.

Moreover, I agree that in the new library we probably should NOT support a second coordinator modifying a transaction OTHER than rolling it back. I can see how the current design in the Java library lends itself naturally to "stateless" coordinators, in that all state is stored on disk in the TransactionItem. This is particularly handy when the library is used to provide transactions-as-a-service, in which the coordinators are stateless HTTP handlers. However, in this case many optimizations in the library that rely on the existence of a common coordinator no longer work, such as those depending on the member variable `fullyAppliedRequests`, which I think are pretty substantial.

Thanks again for patiently demonstrating the cases why this suggestion on checking for APPLIED does not work for the current implementation, and for sharing your advice on the Go version of the library.
