### ISSUE TITLE
Does this library support DAX ?

### ISSUE THREAD

**Issue by tnithinreddy** [awslabs/dynamodb-transactions#44]

**Comment by Yanacek** [comment]
DAX should work with this library without any modification. ConsistentReads go to DynamoDB, and writes and a write-through, so the DAX consistency model should not break the correctness of the library.

That said, it will not improve the performance of transactions, but it will make the writes populate the DAX cache if you are going to do other reads outside of the library. However, if you're doing this, be very careful, since you'll read items in transactions that could be rolled back. See the caveats in the DESIGN.md file. There are some helper functions in Transaction.java like isApplied, isTransient, isLocked, and stripSpecialAttributes that might help you if you're doing that.
