### ISSUE TITLE
Add transaction time out and check if transaction has been timed out before deciding to roll back pending transactions

### ISSUE THREAD

**Issue by tyler-nguyen** [awslabs/dynamodb-transactions#7]
By rolling back the transaction keeping the lock to resolve the contention, the transactions get in the way of each other and make the one keeping the lock cannot complete its transaction.

For example, process A creates a transaction and starts putting requests to it. After that, process B comes in, creates a transaction, puts requests and finds out that the transaction of process A is keeping the lock. It then rolls back the transaction of process A and acquires the lock. Process A now has a rolled back transaction and cannot complete what it is doing.

Normally, it should be "first come, first serve". The transaction of process A should have the right to keep the lock for a defined amount of time. In that time, if any transaction tries to get the lock, it should be the one having to be rolled back, not the transaction of process A. After the time, the transaction of process A will be considered as timed out  transaction, and everything (sweeper and other transactions) can rolled it back.

**Comment by Yanacek** [comment]
We haven't been putting a lot of time into the library, so I'm going to close this feature request unless there is a lot of additional interest for it. For what it's worth, adding an optional time-bound conflict detection heuristic shouldn't be too difficult if anyone wants to take a crack at it. The key is that it should have a maximum timeout, so that if the time delta between the two transactions is long enough, it will roll back the older transaction anyway - this way things don't get stuck forever. That timeout should be made configurable.
